### ISSUE TITLE
Where is the withPingUrl(...)? 

### ISSUE THREAD

**Issue by Gamis214** [pwittchen/NetworkEvents#100]
I have the old version of this Project and i use this declaration of object:

```java
networkEvents = new NetworkEvents(this, bus)
                .withPingUrl(urlJsonObj)
                .withPingTimeout(5000);
```

And I Update today the project and much things are missing.. I use that configuration to now if the server are connected and received a ping... But in this update this function are delete WHY ? Is another way to still use this..?

**Comment by pwittchen** [comment]
I've decided to get rid of this functionality, because it was using `AsyncTask`, which is unreliable mechanism and it's hard to control it's errors. I didn't want to make this library too heavy by adding more reliable solutions under the hood like RxJava. Right now, NetworkEvents is using native functionality available in Android SDK for checking internet connectivity. It uses `ConnectivityManager` for that, so we don't need to ping any url or set ping timeout. Moreover, I wanted to simplify usage of the library. Now, if you want to check internet connection, you can just use code like that:

```java
networkEvents = new NetworkEvents(this, busWrapper)
        .enableInternetCheck();
```

It's described in the documentation in the [enabling internet connection check](https://github.com/pwittchen/NetworkEvents#enabling-internet-connection-check) section.

In addition, now NetworkEvents does not depend on Otto event Bus and we need to create, so called, BusWrapper. You can find instruction how to do this in [Initialize objects](https://github.com/pwittchen/NetworkEvents#initialize-objects) section. I've made that change to reduce dependencies and to allow people use different event buses (e.g. GreenRobot Event Bus).

All changes made in this library are described in the [releases](https://github.com/pwittchen/NetworkEvents/releases) section of this GitHub project and in the [CHANGELOG](https://github.com/pwittchen/NetworkEvents/blob/master/CHANGELOG.md).

You can still use old functionality described in your issue like `withPingUrl(...)` method, `withPingTimeout(...)` method, etc. You just need to use old, legacy version: **1.0.5** of the NetworkEvents. It's available on Maven Central Repository and it's the last version, which has these methods.

**Comment by Gamis214** [comment]
Wouu thank's bro...!!!

**Comment by pwittchen** [comment]
I think, we can close this issue. If you have any more doubts or questions, you can re-open this issue or create another one. :)
