### ISSUE TITLE
no Ethernet Or BluetoothNetwork support ?

### ISSUE THREAD

**Issue by imknown** [pwittchen/NetworkEvents#110]
so i have do some code impl myself..

**Comment by pwittchen** [comment]
I don't understand "Ethernet support" in context of this library. This is library for mobile devices, so I'm not sure if it's possible to connect to ethernet via cable with such device. You can connect to the local network via WiFi no matter if that network is connected to Internet or not. When connection is established, you should receive `ConnectivityStatus.WIFI_CONNECTED` status in the event.

Bluetooth is separate module, so I think it shouldn't be handled within this library, because this library is related to network connections. If you want to have similar API for Bluetooth, NetworkEvents would be good reference point for creating a new library for Bluetooth connections.
