### ISSUE TITLE
Is it possible to add  getInternetConnectionStatus() and getSignalStrength()?

### ISSUE THREAD

**Issue by kamilwlf** [pwittchen/NetworkEvents#60]
Can you add:
 ConnectivityStatus getInternetConnectionStatus() and 
getSignalStrengthChanged()?

sure, I can save the status(e.q in database), but  I prefer to do it on library level

**Comment by pwittchen** [comment]
You can get [ConnectivityStatus](https://github.com/pwittchen/NetworkEvents/blob/master/network-events-library/src/main/java/com/github/pwittchen/networkevents/library/ConnectivityStatus.java) from [ConnectivityChanged](https://github.com/pwittchen/NetworkEvents/blob/master/network-events-library/src/main/java/com/github/pwittchen/networkevents/library/event/ConnectivityChanged.java) event in the following way:

```java
@Subscribe
public void onConnectivityChanged(ConnectivityChanged event) {
   event.getConnectivityStatus()
}
```

ConnectivityStatus can have one of the following values:
* UNKNOWN("unknown"),
* WIFI_CONNECTED("connected to WiFi"),
* WIFI_CONNECTED_HAS_INTERNET("connected to WiFi (Internet available)"),
* WIFI_CONNECTED_HAS_NO_INTERNET("connected to WiFi (Internet not available)"),
* MOBILE_CONNECTED("connected to mobile network"),
* OFFLINE("offline");

You don't really get internet connection status, but you can react on change of connectivity status.

Moreover, you have  `boolean isConnectedToAnyNetwork(Context context)` method in NetworkHelper class. You can use it, when you want to check if user is connected to any network.
You can also use `boolean ping(String url, int timeout)` method for pinging remote website in order to check internet connectivity. This method is used internally by the library.

Is that what you need?

You can react on the Wifi Signal Strength change in the following way:

```java
@Subscribe
public void onWifiSignalStrengthChanged(WifiSignalStrengthChanged event) {
    // do whatever you want - e.g. read fresh list of access points
}
```

I don't see the reason for creating `getSignalStrengthChanged()` method and I don't know what it could actually return.

**Comment by kamilwlf** [comment]
Thank you for your attention to this matter. 

I tried your code and I had android.os.NetworkOnMainThreadException
in this line:
android.os.NetworkOnMainThreadException

btw.
currently in my apss I use this code:
http://paste.ofcode.org/C6THWWb9HWXXRf4sTVdbpp

I have a problem because my function does not detect scenario:
WIFI_CONNECTED_HAS_NO_INTERNET ("Connected to Wi-Fi (not available online)")

and I need to write complex service and discover whether my server is not working or wifi is connected but has no Internet, and when the connection is of poor quality and gets timeuout...too many opportunities

**Comment by pwittchen** [comment]
It was just a quick example. Actually, you need to execute this code in a separate thread instead of the main thread and then you won't see an exception.

I read your another issue: #61 . Now, I understand your problem better, so I think we can resolve it in the new issue and close this one to keep issue tracker clean.
