### ISSUE TITLE
Subscribe for the events must in the implement class instead of super class

### ISSUE THREAD

**Issue by johnwatsondev** [pwittchen/NetworkEvents#88]
My project is used this nice library.
I have a chain of activity: MainActivity extends BaseActivity, BaseActivity extends MintBaseActivity, MintBaseActivity extends XActivity, XActivity extends AppCompatActivity.
They are all abstract class except MainActivity and AppCompatActivity. 
I found a interesting **PROBLEM**(maybe i make a mistake) when used otto as event bus.

```java
@Subscribe
public void onEvent(ConnectivityChanged event) {
    // get connectivity status from event.getConnectivityStatus()
    // or mobile network type via event.getMobileNetworkType()
    // and do whatever you want
}
```

The method below must be in finally implement class instead of super class whether is a abstract class.

Here is my TestRepo --- [TestNetEventLibrary](https://github.com/johnwatsondev/TestNetEventLibrary). You can take a look.

I guess it is the Otto's feature and I'v not read the Otto source. What about your opinion? Thanks in advance!

**Comment by pwittchen** [comment]
I'm not sure if I understood you correctly. This issue is probably related to event bus. When you subscribe the same event in many activities of course, you can place code responsible for registering and unregistering event bus and NetworkEvents in some abstract class from which other classes can derive. This is correct solution. Then, you can just add `@Subscribe` annotation in specific activities. I'm not sure if you can use `@Subscribe` annotation in abstract activity. I haven't encountered such case. Sample app in NetworkEvents repository contains only one activity to provide the simplest example of library usage.

**Comment by johnwatsondev** [comment]
Thanks for reply.

In short, i want extract the receive network changed event method with `@Subscribe` annotation in my abstract BaseActivity. But it not work fine. You can test it with [TestNetEventLibrary](https://github.com/johnwatsondev/TestNetEventLibrary) for a sample.

So, i want the wiki can add this **NOTE** for other developers.

**Comment by pwittchen** [comment]
I think, you can try to test it with a "plain event" with only Otto without NetworkEvents library to verify root cause of the issue. You can also create an issue and ask the question in the repository of Otto at https://github.com/square/otto. They are very responsive and should answer your question.

**Comment by johnwatsondev** [comment]
Yea, thanks for giving me a important clue. I will test it again.

**Comment by johnwatsondev** [comment]
The Otto's [doc](http://square.github.io/otto) have mentioned this NOTE.
>Registering will only find methods on the immediate class type. Unlike the Guava event bus, Otto will not traverse the class hierarchy and add methods from base classes or interfaces that are annotated. This is an explicit design decision to improve performance of the library as well as keep your code simple and unambiguous.

So it's my mistake. Thanks for sharing your idea again.
